version: '2'

services:
  db_postgres_sosemergency:
    image: 'postgres:16'
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=emergency