spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:${PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    user: ${FLYWAY_USERNAME}
    password: ${FLYWAY_PASSWORD}
